# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: gcc-core wget zip
     
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          C:\tools\cygwin\bin\bash.exe --login -c 'pwd'
          C:\tools\cygwin\bin\bash.exe --login -c 'ls -la'
          C:\tools\cygwin\bin\bash.exe --login -c '/usr/bin/wget http://simonowen.com/fdrawcmd/fdrawcmd.h'
          C:\tools\cygwin\bin\bash.exe --login -c 'cp /cygdrive/d/a/epslin/epslin/EpsLin.c /home/runneradmin/'
          C:\tools\cygwin\bin\bash.exe --login -c 'cp /cygdrive/d/a/epslin/epslin/cygwin1.dll /home/runneradmin/'
          C:\tools\cygwin\bin\bash.exe --login -c 'ls -la'
          C:\tools\cygwin\bin\bash.exe --login -c '/usr/bin/gcc EpsLin.c -o epslin.exe'
          C:\tools\cygwin\bin\bash.exe --login -c 'ls -la'
          C:\tools\cygwin\bin\bash.exe --login -c 'zip epslin-win.zip epslin.exe cygwin1.dll'
          C:\tools\cygwin\bin\bash.exe --login -c 'cp /home/runneradmin/epslin-win.zip /cygdrive/d/a/epslin/epslin/'
      - uses: actions/upload-artifact@v2
        with:
          path: ./epslin-win.zip
          name: epslin-win.zip  
